### ISSUE TITLE
Calling the undress proc on an abductor via traitor panel drops the brain of the mob at their feet.

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#2207]
To reproduce:
1. Make someone an abductor via the traitor panel
2. Press the undress button in the abductor bit

No idea if this also applies to naturally made abductors but a verb stripping someone shouldn't make their brain pop out their skull and have them still be alive and walk around.

**Comment by TDcoolguy300** [comment]
It's shit with the verb's exclude from list i believe.

**Comment by Crystalwarrior** [comment]
I think I fixed that in my dismemberment PR, needs to be checked.

**Comment by Spacedong** [comment]
this bug is still not fixed, it drops their butt, heart, and brain, but they're still alive somehow?
